############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
weight = 2
name = "Experience"
url = "/resume"

[[main]]
weight = 3
name = "Projects"
url = "/projects"

[[main]]
name = "Publications"
url = "/publications"
weight = 4

