############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/about-me"
weight = 1

[[main]]
name = "My Programs"
url = "/programs"
weight = 2

[[main]]
name = "Publications"
url = "/publications"
weight = 2

[[main]]
weight = 4
name = "Pages"

[[main]]
parent = "Pages"
name = "Blog"
url = "/blog"

[[main]]
parent = "Pages"
name = "Contact"
url = "/contact"


[[main]]
parent = "Pages"
name = "Categories"
url = "/categories"

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
